spring:
  address: localhost
  port: 8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/insurance_test?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: hrJCr6NLGIXEqTfQPOsh
            client-secret: EgWZaTxKz1
            redirect-uri:  http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response